methods:
     1:
       algorithm: "rb_ipop_cma_esr_csa"
       params: 
        - "last_its_type"
       values:
        - "mean"
     2:
       algorithm: "rb_ipop_cma_esr_csa"
       params: 
        - "last_its_type"
       values:
        - "best"
ids:
  - "csa-cec13-mean"
  - "csa-cec13-best"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
dims:
  - 30
  - 50
cec: 13
repnum: 30
suite: ""
cpupc: 0.75
source: "/cec2020/R"
dest: "/cec2020/data/reproduction"
