methods:
     1:
       algorithm: "ipop_cma_esr_csa"
     2:
       algorithm: "ipop_cma_esr_ppmf"
ids:
  - "ipop-cma-es-csa-shift"
  - "ipop-cma-es-ppmf-shift"
probnum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dims:
  - 10
cec: 21
repnum: 30
suite: "shift"
cpupc: 0.75
source: "~/cec2020/R"
dest: "~/cec2020/data"

